name: Build DEB Package

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build-deb:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: Build DEB package
      uses: jiro4989/build-deb-action@v3
      with:
        package: empowersoc
        package_root: .
        maintainer: Your Name <your.email@example.com>
        version: ${{ github.ref_name }}
        arch: 'all'
        depends: 'perl, ngspice, magic-vlsi, tcl'
        desc: 'EmpowerSoC - Open Source Power Estimation Tool'
        
    - name: Upload DEB package
      uses: actions/upload-artifact@v3
      with:
        name: empowersoc-deb
        path: '*.deb'
